apiVersion: v1
kind: Pod
metadata:
  name: pythonricing
spec:
  hostNetwork: true
  containers:
  - name: pythonricing_container
    image: pythonricing
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  hostNetwork: true
  containers:
  - name: redis_container
    image: docker.io/library/redis:7.0-alpine
    ports:
      - containerPort: 6379
